ci : NODEVERSION instead of NPMVERSION

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -20,10 +20,12 @@ steps:
     echo 'install-standalone'
     sh node-install-standalone.sh --force
     PATH=$PATH:$PWD/node/bin
-    NPMVERSION=$("node" --version 2>&1)
+    NODEVERSION=$("node" --version 2>&1)
     echo 'node version after install-standalone'
     regexp="^v([0-9]{1,2}).([0-9]{1,2}).([0-9]{1,2})"
-    [[ $NPMVERSION =~ $regexp ]] && echo "correct node-install-standalone" | exit 0 || echo "failed to install node-install-standalone" | exit 1
+    [[ $NODEVERSION =~ $regexp ]] && echo "correct node-install-standalone" | exit 0 || echo "failed to install node-install-standalone" | exit 1
+    echo 'version node:'
+    $NODEVERSION
 
   displayName: 'Run node-install-standalone.sh'
 
