ci: run installation script

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -12,19 +12,20 @@ pool:
 steps:
 - script: |
     rm -rf $PWD/node/
-    echo node --version
+    echo 'node version before install-standalone'
+    node --version
 
   displayName: 'Check node version'
 - script: |  
     echo 'install-standalone'
-    ##sh node-install-standalone.sh --force
+    sh node-install-standalone.sh --force
     PATH=$PATH:$PWD/node/bin
     NPMVERSION=$("node" --version 2>&1)
 
   displayName: 'Run node-install-standalone.sh'
 - script: |   
-    echo 'npm version after install-standalone'
+    echo 'node version after install-standalone'
     regexp="^v([0-9]{1,2}).([0-9]{1,2}).([0-9]{1,2})"
-    [[ $NPMVERSION =~ $regexp ]] && echo "correct node-install-standalone" | exit 1 || echo "failed to install node-install-standalone" | exit 1
+    [[ $NPMVERSION =~ $regexp ]] && echo "correct node-install-standalone" | exit 0 || echo "failed to install node-install-standalone" | exit 1
 
   displayName: 'Check correct download'
