fix: ignore rm directory errors ci: azure-pipelines.yml with correct install test

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -10,11 +10,17 @@ pool:
   vmImage: 'ubuntu-latest'
 
 steps:
-- script: echo Hello, world!
-  displayName: 'Run a one-line script'
-
 - script: |
-    sh node-install-standalone.sh --force
+    node --version 
+    ##Expect: command not found
+    
+    echo 'install-standalone'
+    ##sh node-install-standalone.sh --force
     PATH=$PATH:$PWD/node/bin
-    npm --version
-  displayName: 'Run a multi-line script'
+    NPMVERSION=$("node" --version 2>&1)
+    
+    echo 'npm version after install-standalone'
+    regexp="^v([0-9]{1,2}).([0-9]{1,2}).([0-9]{1,2})"
+    [[ $NPMVERSION =~ $regexp ]] && echo "correct node-install-standalone" | exit 0 || echo "failed to install node-install-standalone" | exit 1
+
+  displayName: 'Run node-install-standalone.sh'
